# Theme

theme: jekyll-theme-chirpy
timezone: America/New_York

# URL
url: "https://ikarus702.github.io"
baseurl: ""

# Title
title: Byung-Jun Kim's Webpage
tagline: Welcome to my research portfolio

# Author
author:  
  name: 'Byung-Jun Kim'
  email: 'bkim1@mtu.edu'  # 실제 이메일 넣으세요 (안 넣어도 OK)
 # avatar: 'assets/img/avatar.png'  # 프로필 사진 경로 (없으면 삭제)

# Social links (옵션)
social:
  github: ikarus702
  # fediverse_handle: @ikarus702@sciences.social  # 없으면 주석 처리

# Pagination
paginate: 8
paginate_path: /page:num/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
